name: Deploy Backend

on:
  push:
    branches:
      - deploy
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Publicar Imagen del Backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tienda-backend
        IMAGE_TAG: latest
      run: |
        cd backend
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar Backend en EC2 vía SSM
      env:
        INSTANCE_ID: ${{ secrets.EC2_BACKEND_INSTANCE_ID }}
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: tienda-backend
      run: |
        COMMANDS=$(cat << 'EOF'
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY
        docker pull $REGISTRY/$REPOSITORY:latest
        docker stop tienda-backend || true
        docker rm tienda-backend || true
        docker run -d --name tienda-backend -p 3000:3000 $REGISTRY/$REPOSITORY:latest
        EOF
        )
        
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=[$COMMANDS]" \
          --comment "Despliegue automatico Backend"